FROM python:3.10-slim

WORKDIR /app
COPY app.py sender.py spam_filter.joblib ./

RUN pip install --no-cache-dir streamlit joblib scikit-learn

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
